from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IAgentRepo(Protocol):
    def get(self, agent_id: str) -> Optional[dict]: ...
    def claim(self, agent_id: str, fields: dict) -> None: ...
    def update_heartbeat(self, agent_id: str, reactivate: bool, now_iso: str) -> None: ...
    def set_active_until(self, agent_id: str, active_until: int) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list: ...
    def mark_inactive(self, agent_id: str) -> bool: ...
    def scan_stale_active(self, cutoff_iso: str) -> list: ...
    def create(self, agent: dict) -> None: ...
    def update_policy(self, agent_id: str, mode: str, approved_commands: list) -> None: ...


@runtime_checkable
class IJobRepo(Protocol):
    def create(self, job: dict) -> None: ...
    def get(self, job_id: str) -> Optional[dict]: ...
    def set_running(self, job_id: str, started_at: str) -> bool: ...
    def set_result(self, job_id: str, fields: dict) -> None: ...
    def mark_expired(self, job_id: str) -> None: ...
    def get_pending_for_agent(self, agent_id: str) -> list: ...
    def list_by_tenant(self, tenant_id: str, agent_id: Optional[str], limit: int) -> list: ...


@runtime_checkable
class ITokenRepo(Protocol):
    def get_by_hash(self, token_hash: str) -> Optional[dict]: ...
    def create(self, token: dict) -> None: ...
