from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IAgentRepo(Protocol):
    def get(self, agent_id: str) -> Optional[dict]: ...
    def claim(self, agent_id: str, fields: dict) -> None: ...
    def update_heartbeat(self, agent_id: str, reactivate: bool, now_iso: str, agent_version: Optional[str] = None, running_as_root: Optional[bool] = None) -> None: ...
    def set_active_until(self, agent_id: str, active_until: int) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list: ...
    def mark_inactive(self, agent_id: str) -> bool: ...
    def scan_stale_active(self, cutoff_iso: str) -> list: ...
    def create(self, agent: dict) -> None: ...
    def update_policy(self, agent_id: str, mode: str) -> None: ...
    def reissue_install_token(self, agent_id: str, install_token_hash: str, expires_at: int) -> None: ...
    def delete(self, agent_id: str) -> None: ...
    def set_tags(self, agent_id: str, tags: list) -> None: ...


@runtime_checkable
class IJobRepo(Protocol):
    def create(self, job: dict) -> None: ...
    def get(self, job_id: str) -> Optional[dict]: ...
    def set_running(self, job_id: str, started_at: str) -> bool: ...
    def set_result(self, job_id: str, fields: dict) -> None: ...
    def mark_expired(self, job_id: str) -> None: ...
    def get_pending_for_agent(self, agent_id: str) -> list: ...
    def list_by_tenant(self, tenant_id: str, agent_id: Optional[str], limit: int) -> list: ...


@runtime_checkable
class ITenantRepo(Protocol):
    def get(self, tenant_id: str) -> Optional[dict]: ...
    def create(self, tenant: dict) -> None: ...
    def list_all(self) -> list: ...


@runtime_checkable
class IUserRepo(Protocol):
    def get(self, user_id: str) -> Optional[dict]: ...
    def get_by_hash(self, token_hash: str) -> Optional[dict]: ...
    def create(self, user: dict) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list: ...
    def update_token_hash(self, user_id: str, token_hash: str) -> None: ...
    def delete(self, user_id: str) -> None: ...
    def set_allowed_agents(self, user_id: str, agent_ids: list) -> None: ...
    def remove_agent_from_all_users(self, agent_id: str, tenant_id: str) -> None: ...


@runtime_checkable
class IApprovalRepo(Protocol):
    def create(self, approval: dict) -> None: ...
    def get(self, approval_id: str) -> Optional[dict]: ...
    def exists_pending(self, agent_id: str, command: str) -> bool: ...
    def list_by_agent(self, agent_id: str, status: Optional[str] = None, requested_by: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> list: ...
    def list_by_tenant(self, tenant_id: str, agent_id: Optional[str] = None, status: Optional[str] = None, requested_by: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> list: ...
    def update_status(self, approval_id: str, status: str, reviewed_at: str, reviewed_by: str, expires_at: Optional[str] = None) -> None: ...
    def delete(self, approval_id: str) -> None: ...
