from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class IAgentRepo(Protocol):
    def get(self, agent_id: str) -> Optional[dict]: ...
    def get_by_install_token_hash(self, install_token_hash: str) -> Optional[dict]: ...
    def get_by_agent_token_hash(self, agent_token_hash: str) -> Optional[dict]: ...
    def claim(self, agent_id: str, fields: dict) -> None: ...
    def update_heartbeat(self, agent_id: str, reactivate: bool, now_iso: str, agent_version: Optional[str] = None, running_as_root: Optional[bool] = None) -> None: ...
    def set_active_until(self, agent_id: str, active_until: int) -> None: ...
    def set_k8s_permissions(self, agent_id: str, permissions: dict, perm_hash: str) -> None: ...
    def acknowledge_k8s_permissions(self, agent_id: str, perm_hash: str) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list: ...
    def list_by_fleet(self, fleet_id: str) -> list: ...
    def fleet_member_groups(self, tenant_id: str) -> list: ...
    def mark_inactive(self, agent_id: str) -> bool: ...
    def scan_stale_active(self, cutoff_iso: str) -> list: ...
    def create(self, agent: dict) -> None: ...
    def update_policy(self, agent_id: str, mode: str) -> None: ...
    def request_rotation(self, agent_id: str) -> None: ...
    def reissue_install_token(self, agent_id: str, install_token_hash: str, expires_at: int) -> None: ...
    def set_status(self, agent_id: str, status: str) -> None: ...
    def delete(self, agent_id: str) -> None: ...
    def set_tags(self, agent_id: str, tags: list) -> None: ...
    def set_grants_exception(self, agent_id: str, signature) -> None: ...


@runtime_checkable
class IJobRepo(Protocol):
    def create(self, job: dict) -> None: ...
    def get(self, job_id: str) -> Optional[dict]: ...
    def set_running(self, job_id: str, started_at: str) -> bool: ...
    def set_result(self, job_id: str, fields: dict) -> None: ...
    def mark_expired(self, job_id: str) -> None: ...
    def release_wave(self, run_id: str, wave: int) -> list: ...
    def cancel_staged(self, run_id: str) -> int: ...
    def expire_stale(self, pending_cutoff_iso: str) -> int: ...
    def delete_stale(self, before_iso: str, tenant_id: Optional[str] = None) -> int: ...
    def get_pending_for_agent(self, agent_id: str) -> list: ...
    def list_by_tenant(self, tenant_id: str, agent_id: Optional[str], limit: int) -> list: ...
    def list_by_run(self, tenant_id: str, run_id: str) -> list: ...


@runtime_checkable
class IRunRepo(Protocol):
    def create(self, run: dict) -> None: ...
    def get(self, run_id: str) -> Optional[dict]: ...
    def set_counts(self, run_id: str, state: str, counts: dict, current_wave: Optional[int] = None) -> None: ...
    def set_state(self, run_id: str, state: str) -> None: ...
    def list_by_tenant(self, tenant_id: str, limit: int = 50, cursor: Optional[str] = None) -> list: ...
    def list_by_fleet(self, fleet_id: str, limit: int = 50, cursor: Optional[str] = None) -> list: ...
    def delete_stale(self, before_iso: str, tenant_id: Optional[str] = None) -> int: ...


@runtime_checkable
class ITenantRepo(Protocol):
    def get(self, tenant_id: str) -> Optional[dict]: ...
    def get_by_name(self, name: str) -> Optional[dict]: ...
    def create(self, tenant: dict) -> None: ...
    def list_all(self) -> list: ...
    def set_settings(self, tenant_id: str, settings: dict) -> None: ...


@runtime_checkable
class IUserRepo(Protocol):
    def get(self, user_id: str) -> Optional[dict]: ...
    def create(self, user: dict) -> None: ...
    def list_by_tenant(self, tenant_id: str) -> list: ...
    def delete(self, user_id: str) -> None: ...
    def set_allowed_agents(self, user_id: str, agent_ids: list) -> None: ...
    def set_agent_access(self, user_id: str, readwrite_agent_ids, readonly_agent_ids,
                         readwrite_fleet_ids=None, readonly_fleet_ids=None) -> None: ...
    def remove_agent_from_all_users(self, agent_id: str, tenant_id: str) -> None: ...


@runtime_checkable
class IApprovalRepo(Protocol):
    def create(self, approval: dict) -> None: ...
    def get(self, approval_id: str) -> Optional[dict]: ...
    def exists_pending(self, agent_id: str, command: str) -> bool: ...
    def exists_pending_fleet(self, fleet_id: str, command: str) -> bool: ...
    def list_by_agent(self, agent_id: str, status: Optional[str] = None, requested_by: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> list: ...
    def list_by_fleet(self, fleet_id: str, status: Optional[str] = None, requested_by: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> list: ...
    def list_by_tenant(self, tenant_id: str, agent_id: Optional[str] = None, status: Optional[str] = None, requested_by: Optional[str] = None, limit: Optional[int] = None, cursor: Optional[str] = None) -> list: ...
    def search_by_tenant(self, tenant_id: str, *, status: Optional[str] = None, agent_id: Optional[str] = None, agent_ids: Optional[list] = None, fleet_id: Optional[str] = None, fleet_ids: Optional[list] = None, scope: Optional[str] = None, requested_by: Optional[str] = None, kind: Optional[str] = None, q: Optional[str] = None, limit: int = 20, offset: int = 0) -> tuple: ...
    def update_status(self, approval_id: str, status: str, reviewed_at: str, reviewed_by: str, expires_at: Optional[str] = None) -> None: ...
    def mark_expired(self, now_iso: str) -> int: ...
    def delete_stale(self, before_iso: str, tenant_id: Optional[str] = None) -> int: ...
    def delete(self, approval_id: str) -> None: ...
    def delete_by_agent(self, agent_id: str) -> int: ...
    def delete_by_fleet(self, fleet_id: str) -> int: ...
