apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reach-agent.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reach-agent.labels" . | nindent 4 }}
type: Opaque
